//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalekServer3.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class TblBlog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblBlog()
        {
            this.TblBlogCommentRels = new HashSet<TblBlogCommentRel>();
            this.TblBlogKeywordRels = new HashSet<TblBlogKeywordRel>();
        }
    
        public int id { get; set; }
        public string MainImage { get; set; }
        public string Title { get; set; }
        [AllowHtml]
        public string Body { get; set; }
        public int LikeCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBlogCommentRel> TblBlogCommentRels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBlogKeywordRel> TblBlogKeywordRels { get; set; }
    }
}
