//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalekServer3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblComment()
        {
            this.TblBlogCommentRels = new HashSet<TblBlogCommentRel>();
            this.TblProductCommentRels = new HashSet<TblProductCommentRel>();
        }
    
        public int id { get; set; }
        public int FromId { get; set; }
        public string Body { get; set; }
        public string Date { get; set; }
        public bool IsValid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBlogCommentRel> TblBlogCommentRels { get; set; }
        public virtual TblClient TblClient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductCommentRel> TblProductCommentRels { get; set; }
    }
}
