//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalekServer3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblClientProductRel
    {
        public int id { get; set; }
        public int ClientId { get; set; }
        public int ProductId { get; set; }
        public string Date { get; set; }
        public int Count { get; set; }
        public bool IsFinaly { get; set; }
        public string Name { get; set; }
        public long Price { get; set; }
        public int FactorId { get; set; }
        public Nullable<int> Discount { get; set; }
        public int SumFactor { get; set; }
        public Nullable<int> DiscountId { get; set; }
    
        public virtual TblClient TblClient { get; set; }
    }
}
