//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalekServer3.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class TblConfig
    {
        public int id { get; set; }
        [AllowHtml]
        public string AboutUs { get; set; }
        [AllowHtml]
        public string ContactUs { get; set; }
        [AllowHtml]
        public string SendProduct { get; set; }
    }
}
